# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='certificaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(db_tablespace='CEDULA', max_length=30)),
                ('nombres', models.CharField(db_tablespace='NOMBRES', max_length=70)),
                ('apellido', models.CharField(db_tablespace='APELLIDOS', max_length=70)),
                ('codigo', models.CharField(db_tablespace='CODIGO', max_length=20)),
                ('aprobo', models.CharField(db_tablespace='APROBO', max_length=70)),
                ('fecha', models.DateTimeField(auto_now=True, db_tablespace='fecha')),
                ('horas', models.CharField(db_tablespace='HORAS', max_length=3)),
            ],
            options={
                'db_table': 'certificaciones',
            },
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(db_tablespace='USUARIO', max_length=30)),
                ('clave', models.CharField(db_tablespace='CLAVE', max_length=30)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
