# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificaciones',
            name='fecha',
            field=models.DateTimeField(db_tablespace='fecha'),
        ),
    ]
